### PR TITLE
'Hard' reset of a DHT Sensor via an assigned VCC Pin

### PR DESCRIPTION
**Pull request by Hyperdimensionals**
I added two functions, public **_setPowerReset()_** and private **_resetVCC_pin()_**, which allow for a 'hard' power reset of a DHT sensor when the sensor fails to read the temperature or humidity. The sensor's VCC pin must be plugged into an Arduino digital pin instead of directly into the Arduino's VCC pin, and the pin will be cycled between _digitalWrite()_ LOW and HIGH if reading from the sensor fails.

This came about because in one of my setups controlling a plant terrarium, my DHT22 would periodically fail to read and never recover. However, when I unplugged and reconnected the VCC pin to the sensor, it would read fine again. 

These modifications have fixed my problem and I can once again read from the sensor indefinitely without issues. I am a newb in many respects and understand this could be a problem with something else in my system - whether it be a hardware component or something in my code, but having not found another source, this has been an effective solution. (My setup consists of an UNO R3, a DHT22 sensor, A DS3231 clock module, a LCD 1602 display module, and a 74HC595 Serial to Parallel chip outputting to some relays, all connected with a breadboard.)

The _setPowerReset()_ function can be run once to activate the reset function. It takes 3 arguments: 
  - _VCC_Pin_, which assigns the VCC/power Pin
  - _offInterval_, which assigns the amount of time the VCC power is cycled in milliseconds. It's an unsigned 16 bit int, so the on/off time can theoretically be up to 65535 milliseconds. Optional w/ default of 1000. 
  - _maxTries_, which sets the maximum amount of times the reset will happen while the sensor fails to read before the function 'gives up', up to 255. Optional - don't include this argument, or set to 0, for infinite resets.

The Private function _resetVCC_Pin()_ is what does the actual reset. I placed it at the end of the _readTemperature()_ and _readHumidity()_ functions and it accepts the sensor reading result as an argument, cycling the power if it recieves a NAN. _resetVCC_Pin()_ only runs if a VCC pin is assigned by _setPowerReset()_. 

I also added a public uint8_t variable _resets_ to keep track of the number of times the power has been cycled.

I know that these changes are probably solving a problem that is too esoteric to be considered for the official Adafruit repository, but I thought I'd post it in case it's helpful. I will probably maintain my own repository in case this is useful to anyone else.

### CODE REVIEW

**Comment by docomputing** [comment]
FANTASTIC! Its just what I needed, I have the same problem reading dht22, but hard reset is an excellent workaround ;)

**Comment by caternuson** [comment]
In general, digital pins should not be used for power. If one wants to do this, then can manage the pin via sketch code.

Ideally, the underlying reason for the readings stopping should be investigated so a solution can be worked based on the actual nature of the issue.

**Comment by Hyperdimensionals** [comment]
As far as I understand it, the amperage of the DHT22 is small enough to not be an issue powering from digital pins? Or are there other reasons not to?

 I have yet to find the cause of the occasional failures I experience with the DHT22, and I've been using this code basically 24/7 for almost three years for a climate control system, and as far as I can remember, it has successfully kept my DHT sensor running through every failure (I only noticed them by the reset counter). Even if there were no issues with code causing failures, I see this method as an extra redundancy to keep the sensor reading, but I'd be interested in arguments against it.

That being said, from what I've learned about code cohesion/coupling since writing this, I see how it's better to do this from outside the DHT library. I might rewrite this as a separate module when I have the time.

**Comment by Hyperdimensionals** [comment]
In case anyone sees this who is interested, I did end up making a simple standalone library for this. [Find it here](https://github.com/Hyperdimensionals/HardReset_DHT).

**Pull request closed without merging**
